---
abstract: 'interface to node transformator'
author:
  - 'David Zurborg <zurborg@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-NodeTransformator
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 7.07
  Getopt::Long: 0
  IPC::Run: 0
  Modern::Perl: 0
  POSIX: 0
  Test::More: 0
resources:
  bugtracker: https://github.com/zurborg/libnet-nodetransformator-perl/issues
  homepage: https://metacpan.org/release/Net-NodeTransformator
  repository: https://github.com/zurborg/libnet-nodetransformator-perl.git
version: 0.101
